# Generated by Django 4.2.3 on 2023-09-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nom", models.CharField(max_length=100, verbose_name="Nombres")),
                ("Apell", models.CharField(max_length=100, verbose_name="Apellidos")),
                ("Tit", models.CharField(max_length=100, verbose_name="Titulo")),
                (
                    "Espe",
                    models.CharField(
                        choices=[], max_length=100, verbose_name="Especialidad"
                    ),
                ),
                ("perfil", models.CharField(max_length=100, verbose_name="Perfil")),
                ("tel", models.CharField(max_length=100, verbose_name="Telefono")),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
                ("Descrip", models.TextField(verbose_name="Descripcion")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Acerca de mi",
                "verbose_name_plural": "Acerca de mi",
                "ordering": ["-created"],
            },
        ),
    ]
