# Generated by Django 4.2.3 on 2023-09-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="Espe",
            field=models.CharField(max_length=100, verbose_name="Especialidad"),
        ),
        migrations.CreateModel(
            name="Especialidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Espe", models.CharField(max_length=100, verbose_name="Especialidad")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                ("about", models.ManyToManyField(to="core.about")),
            ],
            options={
                "verbose_name": "Acerca de mi",
                "verbose_name_plural": "Acerca de mi",
                "ordering": ["-created"],
            },
        ),
    ]
