# Generated by Django 4.2.3 on 2023-09-17 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_about_espe_especialidad"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="especialidad",
            options={
                "ordering": ["-created"],
                "verbose_name": "Especialidad",
                "verbose_name_plural": "Especialidades",
            },
        ),
        migrations.RemoveField(
            model_name="about",
            name="Espe",
        ),
    ]
