# Generated by Django 4.2.3 on 2023-09-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_especialidad_options_remove_about_espe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lenguaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Leng", models.CharField(max_length=100, verbose_name="Lenguajes")),
                (
                    "porc",
                    models.IntegerField(max_length=100, verbose_name="Porcentaje"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                ("about", models.ManyToManyField(to="core.about")),
            ],
            options={
                "verbose_name": "Lenguaje",
                "verbose_name_plural": "Lenguajes",
                "ordering": ["-created"],
            },
        ),
    ]
