# Generated by Django 4.2.3 on 2023-09-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_lenguaje_porc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msj", models.TextField(verbose_name="Mensaje")),
                ("drc", models.CharField(max_length=200, verbose_name="Direccion")),
                (
                    "fcb",
                    models.URLField(max_length=300, verbose_name="Enlace a Facebook"),
                ),
                (
                    "itg",
                    models.URLField(max_length=300, verbose_name="Enlace a Instagram"),
                ),
                (
                    "wsp",
                    models.URLField(max_length=300, verbose_name="Enlace a Whatsapp"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                ("about", models.ManyToManyField(to="core.about")),
            ],
            options={
                "verbose_name": "Contacto",
                "verbose_name_plural": "Contactos",
                "ordering": ["-created"],
            },
        ),
    ]
