# Generated by Django 4.2.3 on 2023-09-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_servicio_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portafolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del proyecto"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(max_length=100, verbose_name="Tipo de proyecto"),
                ),
                ("cliente", models.CharField(max_length=100, verbose_name="Cliente")),
                ("fecha", models.DateField(verbose_name="Fecha de creacion")),
                ("url", models.UUIDField(verbose_name="URL")),
                ("detall", models.TextField(verbose_name="Detalle")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                ("about", models.ManyToManyField(to="core.about")),
            ],
            options={
                "verbose_name": "Portafolio",
                "verbose_name_plural": "Portafolios",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Imagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img1", models.ImageField(upload_to="img/", verbose_name="Imagen 1")),
                ("img2", models.ImageField(upload_to="img/", verbose_name="Imagen 2")),
                ("img3", models.ImageField(upload_to="img/", verbose_name="Imagen 3")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificacion"
                    ),
                ),
                ("portafolio", models.ManyToManyField(to="core.portafolio")),
            ],
            options={
                "verbose_name": "Imagen",
                "verbose_name_plural": "Imagenes",
                "ordering": ["-created"],
            },
        ),
    ]
