# Generated by Django 4.2.3 on 2023-09-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_portafolio_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portafolio",
            name="url",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="URL"
            ),
        ),
    ]
