# Generated by Django 4.2.3 on 2023-09-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_imagen_nombre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagen",
            name="img1",
        ),
        migrations.RemoveField(
            model_name="imagen",
            name="img2",
        ),
        migrations.RemoveField(
            model_name="imagen",
            name="img3",
        ),
        migrations.AddField(
            model_name="imagen",
            name="img",
            field=models.ImageField(default=1, upload_to="img/", verbose_name="Imagen"),
            preserve_default=False,
        ),
    ]
