# Generated by Django 4.2.3 on 2023-09-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_imagen_img1_remove_imagen_img2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portafolio",
            name="img1",
            field=models.ImageField(
                default=1, upload_to="img/", verbose_name="Imagen 1"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portafolio",
            name="img2",
            field=models.ImageField(
                default=1, upload_to="img/", verbose_name="Imagen 2"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portafolio",
            name="img3",
            field=models.ImageField(
                default=1, upload_to="img/", verbose_name="Imagen 3"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Imagen",
        ),
    ]
